# Generated by Django 3.2.9 on 2021-11-17 10:43

from django.db import migrations, models
import django.utils.timezone
import zest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name', max_length=50)),
                ('college_name', models.CharField(choices=[('SRMS CET', 'SRMS CET'), ('SRMS CERT', 'SRMS UNNAO'), ('SRMS UNNAO', 'SRMS UNNAO'), ('SRMS IMS', 'SRMS IMS'), ('SRMS NURSING', 'SRMS NURSING')], help_text='Select College', max_length=100)),
                ('roll_no', models.IntegerField(unique=True)),
                ('batch', models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017')], help_text='Select Batch', max_length=25)),
                ('course', models.CharField(choices=[('B.Tech.', 'B.Tech.'), ('M.Tech.', 'M.Tech.'), ('B.Pharma', 'B.Pharma'), ('M.Pharma', 'M.Pharma'), ('MBA', 'MBA')], help_text='Select Course', max_length=25)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EC', 'EC'), ('EN', 'EN'), ('ME', 'ME'), ('NA', 'NA')], help_text='Select Branch', max_length=50)),
                ('phone', models.IntegerField(help_text='Enter Mobile No', validators=[zest.models.validate_phone])),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
