# Generated by Django 3.2.9 on 2021-11-23 17:27

from django.db import migrations, models
import zest.models


class Migration(migrations.Migration):

    dependencies = [
        ('zest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pid',
            name='phone',
            field=models.BigIntegerField(help_text='Enter Mobile No', validators=[zest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='pid',
            name='roll_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
