# Generated by Django 3.2.7 on 2021-11-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zest', '0002_auto_20211120_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pid',
            name='college_name',
            field=models.CharField(choices=[('SRMS CET', 'SRMS CET'), ('SRMS CETR', 'SRMS CETR'), ('SRMS UNNAO', 'SRMS UNNAO'), ('SRMS IMS', 'SRMS IMS'), ('SRMS NURSING', 'SRMS NURSING'), ('OTHER', 'OTHER')], help_text='Select College', max_length=100),
        ),
        migrations.AlterField(
            model_name='tid',
            name='college_name',
            field=models.CharField(choices=[('SRMS CET', 'SRMS CET'), ('SRMS CETR', 'SRMS CETR'), ('SRMS UNNAO', 'SRMS UNNAO'), ('SRMS IMS', 'SRMS IMS'), ('SRMS NURSING', 'SRMS NURSING'), ('OTHER', 'OTHER')], help_text='Select College', max_length=100),
        ),
    ]
