# Generated by Django 3.2.9 on 2021-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zest', '0003_auto_20211122_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='pid',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', help_text='Select Gender', max_length=10),
            preserve_default=False,
        ),
    ]
