# Generated by Django 3.2.9 on 2021-11-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zest', '0003_alter_tid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
