# Generated by Django 3.2.9 on 2021-11-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zest', '0004_alter_tid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Select College', max_length=100)),
                ('pid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid_event', to='zest.pid')),
            ],
        ),
    ]
