# Generated by Django 3.2.9 on 2021-11-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zest', '0005_individual_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_event',
            name='event_name',
            field=models.CharField(choices=[('Solo Dance', 'Solo Dance')], help_text='Enter Event Name', max_length=100),
        ),
        migrations.CreateModel(
            name='Team_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('Group Dance', 'Group Dance')], help_text='Enter Event Name', max_length=100)),
                ('tid', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tid_event', to='zest.tid')),
            ],
        ),
    ]
