# Generated by Django 3.2.9 on 2021-11-20 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zest', '0006_auto_20211119_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='tid',
            name='generated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gereted_tid', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual_event',
            name='event_name',
            field=models.CharField(help_text='Enter Event Name', max_length=100),
        ),
    ]
